# yaml-language-server: $schema=./appConfig.schema.json
Listen: :8080
AppName: HttpTaskExecutioner
RoutePrefix: api/build
Tasks:
  - TaskKey: buildBackend # required, unique, must be `0-9a-zA-Z-_.`, used for logs entries
    Route: repositoryname # Optional, must be `0-9a-zA-Z-_.`, registers the route `{{RoutePrefix}}/tasks/{{Route}}`
    Tests: # Optional, must pass all criteria in order to be run
      Header: # strict string equality test
        "X-Api-Secret": "secret-value"
      JSONBody:
        - Key: $.ref
          Value: refs/heads/master
        - Key: $.repository.url
          Value: https://github.com/my_username/my_repository
    RunnerExecutable: /bin/bash
    MaxRunSeconds: 600
    Args:
      - TASKS/buildBackend.sh # relative path to cwd or absolute path
